server:
  port: 19001

spring:
  application:
    name: userservice
  config:
    activate:
      on-profile: prod
    import:
      - optional:classpath:.env[.properties]
      - optional:configserver:${CONFIG_SERVER_URL:http://pagely-config:8888}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${USER_DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  kafka:
    bootstrap-servers: ${KAFKA_EXTERNAL_HOST:host.docker.internal}:${KAFKA_EXTERNAL_PORT}
    
outbox:
  poll-interval-ms: 5000  # 5초


logging:
  level:
    org.flywaydb: info

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://pagely-eureka:8000/eureka/}

init:
  admin:
    id: ${ADMIN_ID}
    password: ${ADMIN_PASSWORD}
